name: Push Automatix

# This workflow is only used to create images with version tag for the products in Automatix Detect and Scan!

on:
  push:
    tags: ["v*"]

jobs:
  build-redis-server:
    name: Build and Push Redis Server to Greenbone Registry
    uses: greenbone/workflows/.github/workflows/container-build-push-2nd-gen.yml@main
    with:
      build-docker-file: ./redis-server/Dockerfile
      build-context: ./redis-server
      image-url: openvas-detect-dev/redis-server
      image-labels: |
        org.opencontainers.image.vendor=Greenbone
        org.opencontainers.image.documentation=https://greenbone.github.io/docs/
        org.opencontainers.image.base.name=debian:stable-slim
      service: openvas-redis
    secrets: inherit

  build-gpg-data:
    name: Build and Push gpg Data to Greenbone Registry
    uses: greenbone/workflows/.github/workflows/container-build-push-2nd-gen.yml@main
    with:
      build-docker-file: ./gpg-data/Dockerfile
      build-context: ./gpg-data
      image-url: openvas-detect-dev/gpg-data
      image-labels: |
        org.opencontainers.image.vendor=Greenbone
        org.opencontainers.image.documentation=https://greenbone.github.io/docs/
        org.opencontainers.image.base.name=busybox:stable
      service: openvas-gpg-data
    secrets: inherit
