name: Build and Push to Greenbone Registry

on:
  push:
    branches: [ main ]
    tags: ["v*"]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      ref-name:
        type: string
        description: "The ref to build a container image from. For example a tag v23.0.0."
        required: true
  schedule:
    # rebuild image every sunday
    - cron: "0 0 * * 0"

jobs:
  build-redis-server:
    name: Build and Push Redis Server to Greenbone Registry
    uses: greenbone/workflows/.github/workflows/container-build-push-2nd-gen.yml@2nd-multi-arch
    with:
      build-docker-file: ./redis-server/Dockerfile
      build-context: ./redis-server
      image-url: community/redis-server
      image-labels: |
        org.opencontainers.image.vendor=Greenbone
        org.opencontainers.image.documentation=https://greenbone.github.io/docs/
        org.opencontainers.image.base.name=debian:stable-slim
      ref-name: ${{ inputs.ref-name }}
    secrets:
      COSIGN_KEY_OPENSIGHT: ${{ secrets.COSIGN_KEY_OPENSIGHT }}
      COSIGN_KEY_PASSWORD_OPENSIGHT: ${{ secrets.COSIGN_KEY_PASSWORD_OPENSIGHT }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      GREENBONE_REGISTRY: ${{ secrets.GREENBONE_REGISTRY }}
      GREENBONE_REGISTRY_USER: ${{ secrets.GREENBONE_REGISTRY_USER }}
      GREENBONE_REGISTRY_TOKEN: ${{ secrets.GREENBONE_REGISTRY_TOKEN }}
      MATTERMOST_WEBHOOK_URL: ${{ secrets.MATTERMOST_WEBHOOK_URL }}

