name: Push Automatix

# This workflow is only used to create images with version tag for the products in Automatix Detect and Scan!

on:
  push:
    tags: ["v*"]

jobs:
  build-sshd:
    name: Push SSHD Container to Automatix
    uses: greenbone/workflows/.github/workflows/container-build-push-2nd-gen.yml@main
    with:
      build-docker-file: ./sshd/Dockerfile
      build-context: ./sshd
      image-url: openvas-scan-dev/sshd
      image-labels: |
        org.opencontainers.image.vendor=Greenbone
        org.opencontainers.image.documentation=https://greenbone.github.io/docs/
        org.opencontainers.image.base.name=debian:stable-slim
      service: openvas-sshd
    secrets: inherit

  build-redis-server:
    name: Push Redis Server to Automatix
    uses: greenbone/workflows/.github/workflows/container-build-push-2nd-gen.yml@main
    with:
      build-docker-file: ./redis-server/Dockerfile
      build-context: ./redis-server
      image-url: openvas-detect-dev/redis-server
      image-labels: |
        org.opencontainers.image.vendor=Greenbone
        org.opencontainers.image.documentation=https://greenbone.github.io/docs/
        org.opencontainers.image.base.name=debian:stable-slim
      service: openvas-redis
    secrets: inherit

  build-gpg-data:
    name: Push GPG Data to Automatix
    needs: build-redis-server
    uses: greenbone/workflows/.github/workflows/container-build-push-2nd-gen.yml@main
    with:
      build-docker-file: ./gpg-data/Dockerfile
      build-context: ./gpg-data
      image-url: openvas-detect-dev/gpg-data
      image-labels: |
        org.opencontainers.image.vendor=Greenbone
        org.opencontainers.image.documentation=https://greenbone.github.io/docs/
        org.opencontainers.image.base.name=busybox:stable
      service: openvas-gpg-data
    secrets: inherit

  build-gsa-nginx:
    name: Push GSA Nginx to Automatix
    needs:
      - build-redis-server
      - build-gpg-data
    uses: greenbone/workflows/.github/workflows/container-build-push-2nd-gen.yml@main
    with:
      build-docker-file: ./nginx/Dockerfile
      build-context: ./nginx
      image-url: openvas-scan-dev/gsa-nginx
      image-labels: |
        org.opencontainers.image.vendor=Greenbone
        org.opencontainers.image.documentation=https://greenbone.github.io/docs/
        org.opencontainers.image.base.name=nginx:stable-trixie
      service: openvas-gsa-nginx
    secrets: inherit
